### ISSUE TITLE
Seemingly wrong specification of GitHub Action for publishing to PyPI / TestPyPI

### ISSUE THREAD

**Issue by lmcmicu** [pypa/packaging.python.org#1108]
The code at [this link](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#publishing-the-distribution-to-pypi-and-testpypi):

```yaml
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
```
Does not match the usage from the README of the [GitHub Action's website](https://github.com/pypa/gh-action-pypi-publish#usage). Further it does not work.

In particular the above code has the following problems:

1. The `user: __token__` field is missing.
2. The specified action should not be taken from the master branch. It should point to a release. Currently the latest is `@release/v1`.
