### ISSUE TITLE
Example package leads to `author` name being munged with `author_email`

### ISSUE THREAD

**Issue by bwoodsend** [pypa/packaging.python.org#1134]
Following the example package from [here](https://packaging.python.org/en/latest/tutorials/packaging-projects/), in particular the method of specifier author/email it demonstrates causes `pip show` to get confused. An example `pyproject.toml`:

```toml
# pyproject.toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "test-package"
version = "0.0.1"
authors = [
  { name="Example Author", email="author@example.com" },
]
```
which when installed, reports the `Author` field as blank and the author's name + email as the email field.
```fish
> pip install -q .
> pip show test-package
Name: test-package
Version: 0.0.1
Summary: 
Home-page: 
Author: 
Author-email: Example Author <author@example.com>
License: 
Location: /usr/local/lib/python3.10/site-packages
Requires: 
Required-by: 
```
`dict(importlib.metadata.distribution("test-package"))` gives the same pattern. This happens irregardless of build backend. What is the reasoning behind this discrepancy? Is the `Author` field in packaging land being phased out or is this a bug somwhere?
